project:
  type: book
  output-dir: docs

execute:
  cache: true
  
book:
  title: "BST 260 Introduction to Data Science"
  subtitle: "2023 Notes"
  author: "Rafael Irizarry"
  date: "8/19/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - schedule.qmd
    - 01-quarto.qmd
    - 02-unix.qmd
    - 03-git.qmd
    - 04-r-basics.qmd
    - 05-vectorization.qmd
    - 06-tidyverse.qmd
    - 07-dates-and-times.qmd
    - 08-importing-data.qmd
    - 09-data-table.qmd
    - pset1.qmd
    - 10-distributions.qmd
    - 11-ggplot2.qmd
    - 12-dataviz-principles.qmd
    - 13-wrangling.qmd
    - 14-web-scraping.qmd
    - 15-locales.qmd
    - 16-text-mining.qmd
    
  reader-mode: true
  site-url: http://datasciencelabs.github.io/2023
  repo-url: https://github.com/datasciencelabs/2023
  repo-branch: main
  repo-actions: [source, issue]
  sidebar:
    collapse-level: 1
 
format:
  html:
    theme: 
    - cosmo
    - r4ds.scss

editor: source

